# Generated by Django 3.1.1 on 2020-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201129_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.TextField(),
        ),
    ]
