# Generated by Django 3.1.1 on 2020-11-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20201110_0920'),
        ('game', '0008_auto_20201129_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.ia'),
        ),
        migrations.AlterField(
            model_name='player',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connection.utilisateur'),
        ),
    ]
