# Generated by Django 3.1.1 on 2020-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201129_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ia',
            name='Q_table',
        ),
    ]
