# Generated by Django 3.1.1 on 2020-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_ia_q_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Q_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board', models.TextField()),
                ('PosP1', models.CharField(max_length=5)),
                ('PosP2', models.CharField(max_length=5)),
                ('Player_Turn', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('Up', models.FloatField()),
                ('Down', models.FloatField()),
                ('Right', models.FloatField()),
                ('Left', models.FloatField()),
            ],
            options={
                'unique_together': {('board', 'PosP1', 'PosP2', 'Player_Turn')},
            },
        ),
    ]
