# Generated by Django 3.1.1 on 2020-12-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20201201_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
