# Generated by Django 3.1.1 on 2020-12-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20201201_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Q_table',
            new_name='Qtable',
        ),
    ]
