# Generated by Django 3.1.1 on 2020-12-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20201201_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qtable',
            old_name='Down',
            new_name='down',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='Left',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='PlayerTurn',
            new_name='playerTurn',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='PosP1',
            new_name='posP1',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='PosP2',
            new_name='posP2',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='Right',
            new_name='right',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='Up',
            new_name='up',
        ),
        migrations.AlterUniqueTogether(
            name='qtable',
            unique_together={('board', 'posP1', 'posP2', 'playerTurn')},
        ),
    ]
