# Generated by Django 3.1.1 on 2020-12-28 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20201210_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1Box',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='player2Box',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 28, 10, 11, 17, 419644)),
        ),
    ]
