# Generated by Django 3.1.1 on 2020-12-28 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20201228_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 28, 10, 11, 50, 86563)),
        ),
    ]
