# Generated by Django 3.1.1 on 2020-12-28 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20201228_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='maxBoxTaken',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='maxBoxTakenWithArea',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 28, 10, 17, 20, 817803)),
        ),
    ]
