# Generated by Django 3.1.1 on 2021-01-17 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20201228_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='maxBoxTaken',
        ),
        migrations.RemoveField(
            model_name='game',
            name='maxBoxTakenWithArea',
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 17, 15, 44, 24, 684786)),
        ),
    ]
