# Generated by Django 3.1.1 on 2021-01-17 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20210117_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.RemoveField(
            model_name='game',
            name='currentPlayer',
        ),
        migrations.AddField(
            model_name='game',
            name='maxBoxTakenWithArea',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 17, 16, 2, 29, 414782)),
        ),
    ]
