# Generated by Django 3.1.1 on 2021-01-17 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20210117_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 17, 16, 30, 46, 682702)),
        ),
        migrations.AlterField(
            model_name='qtable',
            name='board',
            field=models.TextField(default=''),
        ),
    ]
