# Generated by Django 3.1.1 on 2021-01-17 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20210117_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='current_player',
            new_name='currentPlayer',
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 17, 16, 35, 5, 690597)),
        ),
    ]
