# Generated by Django 3.1.1 on 2021-04-07 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20210117_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player1Box',
            new_name='player1BoxTotal',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2Box',
            new_name='player1BoxTurn',
        ),
        migrations.AddField(
            model_name='game',
            name='player2BoxTotal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='player2BoxTurn',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 4, 7, 18, 26, 50, 264459)),
        ),
    ]
