# Generated by Django 3.1.1 on 2021-04-12 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20210408_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.TimeField(default=datetime.datetime(1997, 11, 25, 0, 0)),
        ),
    ]
