# Generated by Django 3.1.1 on 2021-04-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20210412_1656'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qtable',
            unique_together=set(),
        ),
    ]
