# Generated by Django 3.1.1 on 2021-04-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_auto_20210416_0011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qtable',
            unique_together={('board', 'posP1', 'posP2', 'playerTurn')},
        ),
    ]
