# Generated by Django 3.1.1 on 2021-04-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_auto_20210419_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qtable',
            unique_together={('board', 'posP1', 'posP2', 'playerTurn')},
        ),
    ]
