# Generated by Django 3.1.1 on 2021-04-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_auto_20210419_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qtable',
            unique_together=set(),
        ),
    ]
