# Generated by Django 3.1.1 on 2021-04-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_auto_20210419_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='currentPlayer',
            new_name='current_player',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='iaInfo',
            new_name='ia_info',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='maxBoxTakenWithArea',
            new_name='max_box_taken_with_area',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player1BoxTotal',
            new_name='player1_box_total',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player1BoxTurn',
            new_name='player1_box_turn',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2BoxTotal',
            new_name='player2_box_total',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2BoxTurn',
            new_name='player2_box_turn',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='positionPlayer1',
            new_name='position_player1',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='positionPlayer2',
            new_name='position_player2',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='playerTurn',
            new_name='player_turn',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='posP1',
            new_name='pos_p1',
        ),
        migrations.RenameField(
            model_name='qtable',
            old_name='posP2',
            new_name='pos_p2',
        ),
        migrations.AlterUniqueTogether(
            name='qtable',
            unique_together={('board', 'pos_p1', 'pos_p2', 'player_turn')},
        ),
    ]
