# Generated by Django 3.1.1 on 2021-07-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_auto_20210419_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.CharField(max_length=6)),
                ('stp1', models.CharField(max_length=6)),
                ('at', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('atp1', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('eps', models.FloatField(default=0)),
            ],
        ),
    ]
