# Generated by Django 3.1.1 on 2021-07-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_aiinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ia_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_info', to='game.aiinfo'),
        ),
    ]
