# Generated by Django 3.1.1 on 2021-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_auto_20210716_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ia_info',
            field=models.TextField(default=''),
        ),
    ]
