# Generated by Django 3.1.1 on 2021-07-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_auto_20210716_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ia_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_info', to='game.aiinfo'),
        ),
    ]
