# Generated by Django 3.1.1 on 2020-10-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('BL', 'Blue'), ('PK', 'Pink'), ('YW', 'Yellow'), ('GN', 'Green'), ('VT', 'Violet'), ('RD', 'Red'), ('OE', 'Orange'), ('CN', 'Cyan')], default='BL', max_length=2)),
            ],
        ),
    ]
