# Generated by Django 3.1.1 on 2020-11-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
