# Generated by Django 3.1.1 on 2021-04-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_auto_20210419_2141'),
        ('connection', '0004_auto_20201210_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='User',
        ),
    ]
